sampleApplication:
  enabled: true
  baseConfigMapRefName: basic-gpu-preset
  model:
    modelArtifactURI: "hf://meta-llama/Llama-3.2-1B-Instruct"
    modelName: "llama-3-2-1b-instruct"
gateway:
  enabled: false
modelservice:
  enabled: false
redis:
  enabled: false